[gcp_service_account]
type = "service_account"
project_id = "mk-resources"
private_key_id = "5441453dc96ebf9a74ac32e543502ddfb3345124"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCStfug+ysl8W1s
N1epIslQK6hwQihBvjv7Xk2bWBFL3O1B22KW2QJPa8UohDLvV9eBF5p5a+ENcXz0
ChzQgMxjr8WUTZC27jfTXggjG1UVy4QbsM9uMjchVT/pjOl0Ms9RWLqWbldsQ1re
ZTBR0Au7goPu0agybJo+oJMTi25XDU+eOxBp40CG4+leV08VJ9JJ3hviRJcDdOjq
zSeqtkQ30DJI1aY6Xfn4u4drXSohjPfMYNYMFCqmq2WHA8db2ut0Zis2gnD3RWbi
o7KqiKwVwESOtVnKeykSzqdb27JbRy8ZsyxHcj3DuSmoXIiko/h0RInO3b2+z56c
f+RrkybJAgMBAAECggEANOHiBMHkaLXgklxUfcPrOrmx6lz+c8wlhNMWOEODYIwO
/Wkd3W/1lDkthRA55+oK5R5j8RaAtb7Noo2umz2B7wDhwDZBTp8JgmfnmPf2MHf+
c5jE/FyfYKWA9ydy0w6pihHol+bIHl8c9wMUarkKMZm3ArOR5DMfWim5OhdNO5Ul
zi+7Z/+hSHpSzy0mqoNcE0cGJ+OKps6xMzcbL3qgWvNCVgCKP5FlhDKVvNCe9Wy7
1QbE74xhPbbhwXszBuAbL/xQwDP6GdnIVasdTw+KWgh18HqI3tz8wpOmbP0z+KxQ
v+bD8GeQFpYGVz0NwDaMEouncrduYBPJzhhk4vJqjQKBgQDMjG5mf5rwf0M7AGdx
c2/sDypHZrk5ALSm6bx5VTG7dHlikhCZB/4tQBh2ZY6x/oNArMOkk5k2dFbQ2bZK
oD9Q8Ts3jwX3fSIZhscssMXodVK9ehHpRvEUgcO3Cop8TSl/q3V0chpd/okvAPyy
ACy9xRrZthIIlM6STC+B5vNJpwKBgQC3nTBKrvX+FHwHEoYAdxMsEPJi/+NKvSyl
/IKl9i0+rP9jFQI75ExYt3cqu/tQl7CL61zjM/+fF+tnUhQDf+qwx/zKGZdCkYOs
NZSkeABeEWICIl0X6vqlsvJqMXuCC3f5RVkPsnQvgawd1p50QyAhSBMMtz5JAZ/B
dux4Bo46DwKBgDYriqFCcfn2+gsKFFsLQzy013GJVswtz6nUhMFtOnp2Yh8kp5if
cUTykIfqZVvmF0RtfHJ9VDoDnWo5/fjNb3c0K4aPLflY/krcUqsXNZJWX88mINAy
pW3U38v90qcQmEjjU3u/LBRwcEwuar2JJlArfuzhNu1m2z4LRxmT3CJJAoGAauDw
r0hQoGlEGMnLfpHRcyEaNk5E+8hKKQRm+Dvn8ke5EO+1sS8e0bVZhGKP00W42nlS
RF6MOQsvV6ELTU40Slre5rUmuvUA9EjsESBY9mif6CYgkj+RTspvGSlcf0I1v7+C
LATwZIbSrTu0WHCKT1Uo4Yn4k36Cg5a55tPKDjkCgYEAhnhgECJ6lWP4sAfC5H09
eqLGq2VLftluQR2/R1EnHHeIT6s3bdTdcu2/8JgEv+Cksjz4yXheMaFl0EGFscMI
KW+95ReFqLvdmLHa0z5ZTaMXnjjaZJVNAtKb2iY38iRzZTsISnTnf2unRdXdfXUw
qiB3v3WJH52Z2zCB7qOIemY=
-----END PRIVATE KEY-----
"""
client_email = "gcu-app-sl@mk-resources.iam.gserviceaccount.com"
client_id = "114452009893894748638"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/gcu-app-sl%40mk-resources.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[my_secrets]
sheet_id = "1OJUZFb-vDVvn29PQ9h1CG9v3qQ9cm2vq53EfuR4pKSc"



